### ISSUE TITLE
New version on PlatformIO Registry

### ISSUE THREAD

**Issue by nobodywasishere** [out0f0rder/framework-stm32cubewl#1]
Hello,

I realize this is probably not the best place to ask but could you update the package on the [PlatformIO registery](https://registry.platformio.org/tools/out0f0rder/framework-stm32cubewl) to the latest version (v1.1.0)?

**Comment by out0f0rder** [comment]
Updated, but not tested yet.

**Comment by nobodywasishere** [comment]
Thank you!
